name: build and release docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build docs and Generate PDF
      run: chmod -R 777 . && docker run -v .:/honkit ghcr.io/nishidemasami/markdown-docs:v1.1.29 /bin/sh -c "chmod -R 777 . && npx honkit build && npx honkit pdf ./ ./new-architecture-document-for-nexus.pdf"

    - name: Push to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: _book/

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: documents
        path: ./new-architecture-document-for-nexus.pdf

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: PDF Release
        tag_name: pdf_relrase
        generate_release_notes: true
        files: ./new-architecture-document-for-nexus.pdf
